// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJe3psjtkHdFQkoHqQzJHi_yJt-vW77V0',
    appId: '1:361784729994:web:771e48c43dab51c8b82873',
    messagingSenderId: '361784729994',
    projectId: 'justmart-89cd9',
    authDomain: 'justmart-89cd9.firebaseapp.com',
    storageBucket: 'justmart-89cd9.firebasestorage.app',
    measurementId: 'G-V14SRFNNJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdELS3j6wBfbqy2iUdE-4q0zm0HIOwgrs',
    appId: '1:361784729994:android:637e12a2b8a32728b82873',
    messagingSenderId: '361784729994',
    projectId: 'justmart-89cd9',
    storageBucket: 'justmart-89cd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyYpKtihsQ-l-Jy94ywvdtij6jHxocZ5c',
    appId: '1:361784729994:ios:312388fb115cedbbb82873',
    messagingSenderId: '361784729994',
    projectId: 'justmart-89cd9',
    storageBucket: 'justmart-89cd9.firebasestorage.app',
    iosBundleId: 'com.example.justMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyYpKtihsQ-l-Jy94ywvdtij6jHxocZ5c',
    appId: '1:361784729994:ios:312388fb115cedbbb82873',
    messagingSenderId: '361784729994',
    projectId: 'justmart-89cd9',
    storageBucket: 'justmart-89cd9.firebasestorage.app',
    iosBundleId: 'com.example.justMart',
  );
}
